trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Configure_Server
  displayName: 'Configure Server with Ansible'
  steps:
    - script: |
        echo "Installing Ansible..."
        sudo apt-get update
        sudo apt-get install -y ansible
      displayName: 'Install Ansible'

    - script: |
        echo "Running Ansible Playbook..."
        ansible-playbook -i '74.235.62.114,' playbook.yml -u azureuser --extra-vars "ansible_ssh_pass=Password1234!"
      displayName: 'Run Ansible Playbook'

- job: Deploy_Docker_Container
  displayName: 'Deploy Docker Container'
  dependsOn: Configure_Server
  steps:
    - script: |
        echo "Building and Running Docker Container..."
        docker build -t myapp .
        docker run -d -p 80:80 myapp
      displayName: 'Build and Run Docker Container'