trigger:
  - main

pool:
  NAME: 'Azure Pipelines'

jobs:
- job: Configure_Server
  displayName: 'Configure Server with Ansible'
  steps:
    - script: |
        echo "Installing dependencies..."
        sudo apt-get update
        sudo apt-get install -y ansible
      displayName: 'Install Dependencies'

    - script: |
        echo "Testing SSH connection..."
        ssh -o StrictHostKeyChecking=no azureuser@74.235.62.114 echo "SSH connection successful!"
      displayName: 'Test SSH Connection'

    - script: |
        echo "Running Ansible Playbook..."
        ansible-playbook -i '74.235.62.114,' playbook.yml -u azureuser --extra-vars "ansible_ssh_pass=Password1234!" -vvv
      displayName: 'Run Ansible Playbook'

- job: Deploy_Docker_Container
  displayName: 'Deploy Docker Container'
  dependsOn: Configure_Server
  steps:
    - script: |
        echo "Installing Docker..."
        sudo apt-get update
        sudo apt-get install -y docker.io
      displayName: 'Install Docker'

    - script: |
        echo "Building and Running Docker Container..."
        docker build -t myapp .
        docker run -d -p 80:80 myapp
      displayName: 'Build and Run Docker Container'