trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
     ansible-playbook -i '74.235.62.114', playbook.yml -u azureuser --extra-vars "ansible_ssh_pass=Password1234!"
    displayName: 'Configure Server'

  - script: |
     docker build -t myapp .
     docker run -d -p 80:80 myapp
    displayName: 'Deploy Docker Container'